import streamlit as st
import os
import io
import time
import json
import shutil
from datetime import datetime
import pandas as pd
import streamlit.components.v1 as components

from agent import (
    WORKSPACE_DIR,
    VIDEOS_DIR,
    get_available_gemini_models,
    initialize_agent_model,
    web_search,
    web_fetch,
    execute_python_code,
    fs_list_files,
    fs_read_file,
    fs_write_file,
    fs_create_directory,
    fs_delete_path,
    fs_copy_path,
    fs_move_path,
    fs_search_files,
    create_workspace_zip,
    generate_image_url,
    synthesize_ai_video,
    download_media_bytes,
    enhance_prompt_with_gemini,
    transcribe_audio_bytes,
    run_workspace_command,
    get_system_info,
)

st.set_page_config(
    page_title="OmniAgent OS | Autonomous AI Cloud Hub",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    .main-header { font-size: 2.2rem; font-weight: 800; color: #1E88E5; margin-bottom: 0px; }
    .sub-header { font-size: 1.05rem; color: #555; margin-bottom: 20px; }
    .voice-card { padding: 14px; border-radius: 14px; background: #f6f8fb; border: 1px solid #e7ebf0; margin-bottom: 12px; }
    .tool-badge { display:inline-block; padding:4px 8px; border-radius:999px; background:#eef5ff; margin:2px; font-size:.78rem; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# SESSION STATE
# ==========================================
if "chat_messages" not in st.session_state:
    st.session_state.chat_messages = [
        {"role": "assistant", "content": "👋 Greetings! I am **OmniAgent OS 3**. I can research the live web, write/test code, manage workspace files, automate development tasks, generate images/MP4s, and talk with you by voice."}
    ]
if "image_history" not in st.session_state:
    st.session_state.image_history = []
if "video_history" not in st.session_state:
    st.session_state.video_history = []
if "voice_enabled" not in st.session_state:
    st.session_state.voice_enabled = True
if "voice_rate" not in st.session_state:
    st.session_state.voice_rate = 1.0
if "last_agent_model" not in st.session_state:
    st.session_state.last_agent_model = ""


def extract_gemini_text(response) -> str:
    """Safely extract only text parts from a Gemini response.

    The legacy google-generativeai SDK raises:
    ValueError: Could not convert part.function_call to text
    when response.text is accessed on a response containing a function-call part.
    We therefore inspect parts directly and ignore function_call/function_response parts.
    """
    text_chunks = []
    candidates = getattr(response, "candidates", None) or []
    for candidate in candidates:
        content = getattr(candidate, "content", None)
        parts = getattr(content, "parts", None) or []
        for part in parts:
            text = getattr(part, "text", None)
            if isinstance(text, str) and text.strip():
                text_chunks.append(text.strip())
    if text_chunks:
        return "\n\n".join(text_chunks).strip()

    # Only use the convenience .text accessor when no usable text parts were found.
    # Some SDK versions can still expose a plain-text response this way.
    try:
        value = getattr(response, "text", "") or ""
        return value.strip() if isinstance(value, str) else ""
    except (ValueError, TypeError, AttributeError):
        return ""


def speak_browser(text: str, autoplay: bool = False, rate: float = 1.0):
    """Browser-native TTS. Audio is generated by the user's browser; no TTS API is required."""
    payload = json.dumps(text)
    component_html = f"""
    <div style='font-family:system-ui; display:flex; gap:8px; align-items:center; padding:2px;'>
      <button id='speakBtn' style='border:1px solid #d9dee8;border-radius:10px;padding:7px 12px;cursor:pointer;background:white;'>🔊 Speak</button>
      <button id='stopBtn' style='border:1px solid #d9dee8;border-radius:10px;padding:7px 12px;cursor:pointer;background:white;'>⏹ Stop</button>
      <span style='font-size:12px;color:#667085;'>Browser voice output</span>
    </div>
    <script>
      const text = {payload};
      const rate = {float(rate)};
      function speak() {{
        if (!('speechSynthesis' in window)) {{ alert('Speech synthesis is not supported by this browser.'); return; }}
        window.speechSynthesis.cancel();
        const u = new SpeechSynthesisUtterance(text);
        u.rate = rate;
        u.pitch = 1.0;
        u.volume = 1.0;
        const voices = window.speechSynthesis.getVoices();
        const preferred = voices.find(v => /en-IN|en-US|en-GB/i.test(v.lang)) || voices[0];
        if (preferred) u.voice = preferred;
        window.speechSynthesis.speak(u);
      }}
      document.getElementById('speakBtn').onclick = speak;
      document.getElementById('stopBtn').onclick = () => window.speechSynthesis.cancel();
      if ({str(bool(autoplay)).lower()}) setTimeout(speak, 250);
    </script>
    """
    components.html(component_html, height=55, scrolling=False)


# ==========================================
# SIDEBAR
# ==========================================
with st.sidebar:
    st.markdown("### ⚡ OmniAgent Control Core")
    env_api_key = os.getenv("GEMINI_API_KEY", "")
    api_key_input = st.text_input(
        "Google Gemini API Key:",
        value=env_api_key,
        type="password",
        help="Get your key from Google AI Studio.",
    )
    active_api_key = api_key_input.strip() if api_key_input else env_api_key

    available_models = get_available_gemini_models(active_api_key)
    preferred_order = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro"]
    default_idx = next((available_models.index(x) for x in preferred_order if x in available_models), 0)
    model_choice = st.selectbox("Active Gemini Model Tier:", available_models, index=default_idx)

    st.markdown("---")
    st.markdown("#### 🗣️ Voice Assistant")
    st.session_state.voice_enabled = st.toggle("Enable voice replies", value=st.session_state.voice_enabled)
    st.session_state.voice_rate = st.slider("Voice speed", 0.7, 1.4, st.session_state.voice_rate, 0.05)
    st.caption("Voice input uses the browser microphone recorder. Voice output uses browser-native speech synthesis.")

    st.markdown("---")
    st.markdown("#### 🧠 Agent Capabilities")
    for badge in [
        "Live Web", "Web Fetch", "Python Runner", "File Manager", "Copy/Move",
        "Dev Commands", "Image Generator", "MP4 Generator", "Voice I/O"
    ]:
        st.markdown(f"<span class='tool-badge'>{badge}</span>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("#### 📂 Workspace Telemetry")
    file_count = 0
    total_size = 0
    for root, dirs, files in os.walk(WORKSPACE_DIR):
        file_count += len(files)
        for f in files:
            fp = os.path.join(root, f)
            try:
                total_size += os.path.getsize(fp)
            except OSError:
                pass
    col_s1, col_s2 = st.columns(2)
    col_s1.metric("Files", file_count)
    col_s2.metric("Size", f"{round(total_size / 1024, 1)} KB")

    zip_buffer = create_workspace_zip()
    st.download_button(
        label="📦 Export Workspace ZIP",
        data=zip_buffer,
        file_name=f"workspace_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip",
        mime="application/zip",
        use_container_width=True,
    )

    if st.button("🗑️ Reset Workspace", use_container_width=True):
        for item in os.listdir(WORKSPACE_DIR):
            item_path = os.path.join(WORKSPACE_DIR, item)
            if os.path.isfile(item_path) or os.path.islink(item_path):
                os.remove(item_path)
            elif os.path.isdir(item_path):
                shutil.rmtree(item_path)
        os.makedirs(VIDEOS_DIR, exist_ok=True)
        st.success("Workspace reset.")
        st.rerun()

    if st.button("🧹 Clear Chat", use_container_width=True):
        st.session_state.chat_messages = []
        st.rerun()

# ==========================================
# HEADER
# ==========================================
st.markdown("<div class='main-header'>🤖 OmniAgent OS 3</div>", unsafe_allow_html=True)
st.markdown(
    "<div class='sub-header'>Autonomous Agentic AI • Live Web • OpenClaw-style Workspace Automation • Code Runner • Voice Assistant • Image & MP4 Core</div>",
    unsafe_allow_html=True,
)

# ==========================================
# TABS
# ==========================================
tab_chat, tab_code, tab_img, tab_video, tab_files = st.tabs([
    "💬 Autonomous Agent Chat",
    "💻 Code Studio & Runner",
    "🎨 AI Image Studio",
    "🎬 MP4 Video Core",
    "📂 OpenClaw Workspace",
])

# ==========================================
# TAB 1: CHAT + VOICE
# ==========================================
with tab_chat:
    st.caption("OmniAgent can plan and chain actions across web research, code, files and development commands instead of stopping after one response.")
    st.caption("Gemini compatibility mode: conversation context is injected safely into the current request to avoid SDK history-slice errors.")

    # Display conversation. Use a speak control for assistant messages.
    for idx, msg in enumerate(st.session_state.chat_messages):
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            if msg["role"] == "assistant" and st.session_state.voice_enabled:
                speak_browser(msg["content"], autoplay=False, rate=st.session_state.voice_rate)

    st.markdown("<div class='voice-card'><b>🎙️ Voice Input</b><br>Record a question and OmniAgent will transcribe it, then run the same autonomous agent workflow.</div>", unsafe_allow_html=True)
    voice_audio = None
    if hasattr(st, "audio_input"):
        voice_audio = st.audio_input("Press record and speak to OmniAgent", key="voice_recorder")

    voice_col1, voice_col2 = st.columns([3, 1])
    with voice_col1:
        user_prompt = st.chat_input("Ask a question, request web research, or trigger code/file/automation tasks...")
    with voice_col2:
        process_voice = st.button("🎙️ Use Voice", use_container_width=True)

    voice_prompt = ""
    if process_voice and voice_audio:
        if not active_api_key:
            st.error("⚠️ Add a Gemini API key to use voice transcription.")
        else:
            with st.spinner("🎧 Transcribing your voice..."):
                try:
                    voice_prompt = transcribe_audio_bytes(voice_audio.getvalue(), active_api_key)
                    if voice_prompt:
                        st.success(f"Heard: {voice_prompt}")
                except Exception as exc:
                    st.error(f"Voice transcription error: {exc}")
    elif process_voice and not voice_audio:
        st.info("Record a voice message first.")

    effective_prompt = voice_prompt or user_prompt

    if effective_prompt:
        if not active_api_key:
            st.error("⚠️ Please provide a Gemini API Key in the sidebar.")
        else:
            st.session_state.chat_messages.append({"role": "user", "content": effective_prompt})
            with st.chat_message("user"):
                st.markdown(effective_prompt)

            with st.chat_message("assistant"):
                message_placeholder = st.empty()
                status_placeholder = st.empty()
                try:
                    with st.spinner("🤖 OmniAgent is reasoning, using tools, and completing the task..."):
                        agent_model, active_model_used = initialize_agent_model(active_api_key, model_choice)
                        st.session_state.last_agent_model = active_model_used

                        # IMPORTANT SDK COMPATIBILITY FIX:
                        # Some versions of the legacy google-generativeai SDK raise
                        # "TypeError: slice indices must be integers or None or have an __index__ method"
                        # when a hand-built history list is passed to start_chat().
                        # Keep the SDK chat fresh and inject the recent conversation as plain
                        # text context instead. This preserves context without using the
                        # problematic history representation.
                        previous_messages = st.session_state.chat_messages[:-1][-8:]
                        context_blocks = []
                        for past_msg in previous_messages:
                            role = "USER" if past_msg["role"] == "user" else "ASSISTANT"
                            content = str(past_msg.get("content", "")).strip()
                            if content:
                                # Keep the context bounded so large old responses do not
                                # overwhelm the current task.
                                context_blocks.append(f"{role}: {content[:4000]}")
                        conversation_context = "\n".join(context_blocks)

                        prompt_for_model = effective_prompt
                        if conversation_context:
                            prompt_for_model = (
                                "Earlier conversation context (do not repeat unless useful):\n"
                                f"{conversation_context}\n\n"
                                f"CURRENT USER REQUEST:\n{effective_prompt}"
                            )

                        try:
                            chat = agent_model.start_chat(
                                enable_automatic_function_calling=True,
                            )
                            response = chat.send_message(prompt_for_model)
                        except TypeError as sdk_err:
                            # Compatibility retry for older SDK/model combinations.
                            if "slice indices" not in str(sdk_err).lower():
                                raise
                            chat = agent_model.start_chat()
                            response = chat.send_message(prompt_for_model)

                        # IMPORTANT: never call response.text blindly. Gemini tool-calling
                        # responses can contain part.function_call, and the legacy SDK
                        # raises ValueError when converting such a part to text.
                        response_text = extract_gemini_text(response)

                        # In a few legacy SDK/model combinations the returned response can
                        # still contain only a function-call part. Ask the same chat for a
                        # final user-facing answer rather than crashing the UI.
                        if not response_text:
                            try:
                                follow_up = chat.send_message(
                                    "The requested tool work is complete. Now return the final answer to the user in plain text/Markdown. Do not call another tool unless absolutely necessary."
                                )
                                response_text = extract_gemini_text(follow_up)
                            except Exception:
                                response_text = ""

                        if not response_text:
                            response_text = "✅ Task completed, but the model returned no final text. Check the workspace for generated files."

                        message_placeholder.markdown(response_text)
                        st.session_state.chat_messages.append({"role": "assistant", "content": response_text})
                        status_placeholder.success(f"Completed with {active_model_used} • tools enabled")

                        if st.session_state.voice_enabled:
                            speak_browser(response_text, autoplay=False, rate=st.session_state.voice_rate)
                except Exception as e:
                    err_msg = f"⚠️ **Agent Error:** {type(e).__name__}: {e}"
                    message_placeholder.markdown(err_msg)
                    st.session_state.chat_messages.append({"role": "assistant", "content": err_msg})
                    status_placeholder.error("The agent stopped because of a runtime error. Existing workspace changes, if any, are preserved.")

# ==========================================
# TAB 2: CODE STUDIO
# ==========================================
with tab_code:
    st.subheader("💻 Interactive Code Studio & Python Sandbox")
    col_code_left, col_code_right = st.columns([1, 1])
    with col_code_left:
        st.markdown("##### 📝 Code Editor")
        default_py = """import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x) * np.exp(-0.1 * x)

plt.figure(figsize=(8, 4))
plt.plot(x, y, lw=2.5)
plt.title('Autonomous Code Execution Waveform')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
print('Execution completed! Visualization rendered.')
"""
        code_input = st.text_area("Python Script", value=default_py, height=320, key="sandbox_code")
        c1, c2, c3 = st.columns([1, 1, 1])
        run_btn = c1.button("▶️ Run Code", use_container_width=True, type="primary")
        save_as_file = c2.text_input("Filename", value="script.py", label_visibility="collapsed")
        save_btn = c3.button("💾 Save File", use_container_width=True)
        if save_btn:
            st.success(fs_write_file(save_as_file, code_input))

    with col_code_right:
        st.markdown("##### 🖥️ Execution Console")
        if run_btn:
            with st.spinner("Running Python script in workspace..."):
                exec_result = execute_python_code(code_input)
            if exec_result["stdout"]:
                st.markdown("**Console Output:**")
                st.code(exec_result["stdout"], language="text")
            if exec_result["stderr"]:
                st.markdown("**Errors:**")
                if exec_result["success"]:
                    st.warning(exec_result["stderr"])
                else:
                    st.error(exec_result["stderr"])
            if exec_result["has_plots"]:
                st.markdown("**Generated Visual Charts:**")
                for fig in exec_result["plot_figures"]:
                    st.pyplot(fig)
            if exec_result["success"]:
                st.success("Execution finished successfully.")
        else:
            st.info("Click '▶️ Run Code' to execute the script in the workspace.")

    st.markdown("---")
    st.markdown("##### 🛠️ OpenClaw-style Development Command Runner")
    st.caption("Runs an allowlisted command from the workspace, useful for tests/builds such as `python script.py`, `pip install ...`, `npm run build`, `git status`, or `ffmpeg ...`.")
    cmd_col1, cmd_col2 = st.columns([4, 1])
    with cmd_col1:
        workspace_command = st.text_input("Workspace command", placeholder="python -m pytest")
    with cmd_col2:
        cmd_timeout = st.number_input("Timeout (s)", min_value=1, max_value=180, value=60)
    if st.button("⚙️ Run Workspace Command", type="secondary"):
        if workspace_command:
            with st.spinner("Running command..."):
                result = run_workspace_command(workspace_command, int(cmd_timeout))
            st.code(result, language="json")

# ==========================================
# TAB 3: IMAGE STUDIO
# ==========================================
with tab_img:
    st.subheader("🎨 Generative AI Image Studio")
    img_col1, img_col2 = st.columns([1, 1])
    with img_col1:
        img_prompt_input = st.text_area("Image Prompt:", placeholder="e.g., A cybernetic astronaut exploring an illuminated bioluminescent cave, 8k, cinematic lighting", height=120)
        opt1, opt2, opt3 = st.columns(3)
        aspect = opt1.selectbox("Aspect Ratio", ["1:1 (Square)", "16:9 (Landscape)", "9:16 (Portrait)"])
        model_type = opt2.selectbox("Diffusion Model", ["flux", "turbo"])
        custom_seed = opt3.number_input("Seed (0 for random)", min_value=0, max_value=999999, value=0)
        dim_map = {"1:1 (Square)": (1024, 1024), "16:9 (Landscape)": (1280, 720), "9:16 (Portrait)": (720, 1280)}
        w, h = dim_map[aspect]
        b1, b2 = st.columns(2)
        enhance_btn = b1.button("✨ Enhance Prompt", use_container_width=True)
        generate_img_btn = b2.button("🎨 Render Artwork", type="primary", use_container_width=True)
        if enhance_btn:
            if img_prompt_input and active_api_key:
                with st.spinner("Refining prompt with Gemini..."):
                    enhanced = enhance_prompt_with_gemini(img_prompt_input, active_api_key, "image")
                st.success("Prompt Enhanced!")
                st.text_area("Refined Prompt", value=enhanced, height=80)
            else:
                st.warning("Please provide a prompt and Gemini API Key.")
    with img_col2:
        if generate_img_btn and img_prompt_input:
            with st.spinner("Rendering artwork..."):
                seed_val = None if custom_seed == 0 else custom_seed
                image_url = generate_image_url(img_prompt_input, width=w, height=h, seed=seed_val, model=model_type)
                st.image(image_url, caption=f"Prompt: {img_prompt_input}", use_container_width=True)
                img_bytes = download_media_bytes(image_url)
                if img_bytes:
                    st.download_button("📥 Download Full-Res Image", data=img_bytes, file_name=f"art_{int(time.time())}.jpg", mime="image/jpeg", use_container_width=True)
        else:
            st.info("Enter an image description and click 'Render Artwork'.")

# ==========================================
# TAB 4: VIDEO
# ==========================================
with tab_video:
    st.subheader("🎬 Generative MP4 Video Core")
    st.caption("Synthesizes genuine MP4 video files with dynamic cinematic camera trajectories.")
    vid_col1, vid_col2 = st.columns([1, 1])
    with vid_col1:
        vid_prompt_input = st.text_area("Video Concept Prompt:", placeholder="e.g., A futuristic flying supercar speeding through neon cyberpunk Tokyo in the rain, cinematic lighting", height=120)
        v_c1, v_c2, v_c3 = st.columns(3)
        v_motion = v_c1.selectbox("Camera Trajectory", ["Cinematic Zoom In", "Dynamic Pan Right", "Dramatic Tilt Up", "Orbital Pulse"])
        v_duration = v_c2.selectbox("Duration", [3, 4, 5], index=1)
        v_fps = v_c3.selectbox("Frame Rate", [24, 30], index=0)
        generate_vid_btn = st.button("🎬 Synthesize MP4 Video", type="primary", use_container_width=True)
    with vid_col2:
        if generate_vid_btn and vid_prompt_input:
            with st.spinner("🎬 Synthesizing frames and compiling MP4..."):
                vid_path, vid_bytes = synthesize_ai_video(prompt=vid_prompt_input, motion_type=v_motion, duration_seconds=v_duration, fps=v_fps)
            if vid_bytes and vid_path:
                st.success(f"✅ MP4 generated and saved: `{os.path.basename(vid_path)}`")
                st.video(vid_bytes)
                st.download_button("📥 Download MP4 Video File", data=vid_bytes, file_name=os.path.basename(vid_path), mime="video/mp4", use_container_width=True)
            else:
                st.error("Video synthesis could not be completed. Please try again.")
        else:
            st.info("Enter your video prompt and click 'Synthesize MP4 Video'.")

# ==========================================
# TAB 5: WORKSPACE
# ==========================================
with tab_files:
    st.subheader("📂 OpenClaw-style Workspace File Manager")
    st.caption(f"Active Workspace Root: `{WORKSPACE_DIR}`")
    f_action_col1, f_action_col2, f_action_col3 = st.columns([1, 1, 1])

    with f_action_col1:
        with st.expander("➕ Create New File"):
            new_fname = st.text_input("File Path/Name:", placeholder="notes.txt")
            new_fcontent = st.text_area("Initial Content:", height=100)
            if st.button("Create File", use_container_width=True):
                if new_fname:
                    st.success(fs_write_file(new_fname, new_fcontent))
                    st.rerun()
    with f_action_col2:
        with st.expander("📁 Create New Folder"):
            new_dname = st.text_input("Folder Name:", placeholder="data")
            if st.button("Create Folder", use_container_width=True):
                if new_dname:
                    st.success(fs_create_directory(new_dname))
                    st.rerun()
    with f_action_col3:
        with st.expander("📤 Upload File(s)"):
            uploaded_files = st.file_uploader("Upload to workspace", accept_multiple_files=True)
            if uploaded_files:
                for uf in uploaded_files:
                    target_dest = os.path.join(WORKSPACE_DIR, os.path.basename(uf.name))
                    with open(target_dest, "wb") as f:
                        f.write(uf.getbuffer())
                st.success(f"Uploaded {len(uploaded_files)} file(s)!")
                st.rerun()

    st.markdown("---")
    browser_col, editor_col = st.columns([1, 2])
    with browser_col:
        st.markdown("##### 📁 Workspace Tree")
        st.text_area("Directory Tree", value=fs_list_files(), height=260, disabled=True)
        all_files = []
        for r, _, fls in os.walk(WORKSPACE_DIR):
            for fl in fls:
                all_files.append(os.path.relpath(os.path.join(r, fl), WORKSPACE_DIR))
        selected_file = st.selectbox("Select File to View / Edit:", [""] + sorted(all_files))
        if selected_file:
            if st.button("🗑️ Delete Selected File", type="secondary", use_container_width=True):
                st.warning(fs_delete_path(selected_file))
                st.rerun()

    with editor_col:
        st.markdown("##### 📝 Live File Viewer & Editor")
        if selected_file:
            current_content = fs_read_file(selected_file)
            edited_content = st.text_area(f"Editing: {selected_file}", value=current_content, height=300)
            if st.button("💾 Save File Changes", type="primary", use_container_width=True):
                fs_write_file(selected_file, edited_content)
                st.success(f"File '{selected_file}' updated successfully!")
        else:
            st.info("Select a file from the dropdown on the left to read or edit.")

    with st.expander("🔍 Search in Workspace Files"):
        search_q = st.text_input("Enter keyword to search across all workspace files:")
        if search_q:
            st.code(fs_search_files(search_q), language="text")

    with st.expander("ℹ️ Runtime Information"):
        st.code(get_system_info(), language="json")
