import streamlit as st
import os
import io
import time
import json
import re
import shutil
from datetime import datetime
import pandas as pd
import streamlit.components.v1 as components

from agent import (
    WORKSPACE_DIR,
    VIDEOS_DIR,
    get_available_gemini_models,
    initialize_agent_model,
    web_search,
    web_fetch,
    execute_python_code,
    fs_list_files,
    fs_read_file,
    fs_write_file,
    fs_create_directory,
    fs_delete_path,
    fs_copy_path,
    fs_move_path,
    fs_search_files,
    create_workspace_zip,
    generate_image_url,
    synthesize_ai_video,
    download_media_bytes,
    enhance_prompt_with_gemini,
    transcribe_audio_bytes,
    run_workspace_command,
    get_system_info,
    run_gemini_agent, run_text_provider, choose_provider_chain,
    DEFAULT_MODELS, OMNIAGENT_VERSION, transcribe_audio_bytes,
    is_provider_error,
)

st.set_page_config(
    page_title="OmniAgent OS | Autonomous AI Cloud Hub",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    .main-header { font-size: 2.2rem; font-weight: 800; color: #1E88E5; margin-bottom: 0px; }
    .sub-header { font-size: 1.05rem; color: #555; margin-bottom: 20px; }
    .voice-card { padding: 14px; border-radius: 14px; background: #f6f8fb; border: 1px solid #e7ebf0; margin-bottom: 12px; }
    .tool-badge { display:inline-block; padding:4px 8px; border-radius:999px; background:#eef5ff; margin:2px; font-size:.78rem; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# SESSION STATE
# ==========================================
if "chat_messages" not in st.session_state:
    st.session_state.chat_messages = [
        {"role": "assistant", "content": "👋 Greetings! I am **OmniAgent OS 4**. I can research the live web, work with code/files, automate development tasks, use multiple AI providers, and talk with you by voice."}
    ]
if "image_history" not in st.session_state:
    st.session_state.image_history = []
if "video_history" not in st.session_state:
    st.session_state.video_history = []
if "voice_enabled" not in st.session_state:
    st.session_state.voice_enabled = True
if "voice_rate" not in st.session_state:
    st.session_state.voice_rate = 1.0
if "last_agent_model" not in st.session_state:
    st.session_state.last_agent_model = ""


def speak_browser(text: str, autoplay: bool = False, rate: float = 1.0):
    """Browser-native TTS. Audio is generated by the user's browser; no TTS API is required."""
    payload = json.dumps(text)
    component_html = f"""
    <div style='font-family:system-ui; display:flex; gap:8px; align-items:center; padding:2px;'>
      <button id='speakBtn' style='border:1px solid #d9dee8;border-radius:10px;padding:7px 12px;cursor:pointer;background:white;'>🔊 Speak</button>
      <button id='stopBtn' style='border:1px solid #d9dee8;border-radius:10px;padding:7px 12px;cursor:pointer;background:white;'>⏹ Stop</button>
      <span style='font-size:12px;color:#667085;'>Browser voice output</span>
    </div>
    <script>
      const text = {payload};
      const rate = {float(rate)};
      function speak() {{
        if (!('speechSynthesis' in window)) {{ alert('Speech synthesis is not supported by this browser.'); return; }}
        window.speechSynthesis.cancel();
        const u = new SpeechSynthesisUtterance(text);
        u.rate = rate;
        u.pitch = 1.0;
        u.volume = 1.0;
        const voices = window.speechSynthesis.getVoices();
        const preferred = voices.find(v => /en-IN|en-US|en-GB/i.test(v.lang)) || voices[0];
        if (preferred) u.voice = preferred;
        window.speechSynthesis.speak(u);
      }}
      document.getElementById('speakBtn').onclick = speak;
      document.getElementById('stopBtn').onclick = () => window.speechSynthesis.cancel();
      if ({str(bool(autoplay)).lower()}) setTimeout(speak, 250);
    </script>
    """
    components.html(component_html, height=55, scrolling=False)


# ==========================================
# SIDEBAR: MULTI-PROVIDER CONTROL CORE
# ==========================================
with st.sidebar:
    st.markdown("### ⚡ OmniAgent Control Core")
    st.caption(f"OmniAgent OS {OMNIAGENT_VERSION} • Multi-Provider")

    provider_mode = st.selectbox(
        "🧠 AI Provider Mode",
        ["Auto", "Gemini", "Hugging Face", "Groq", "OpenRouter", "Cohere", "LM Studio"],
        index=0,
        help="Auto tries Gemini first, then the configured fallbacks."
    )

    st.markdown("#### 🔑 API Keys & Connections")
    env = os.getenv

    gemini_key = st.text_input("🔵 Google Gemini API Key", value=env("GEMINI_API_KEY", ""), type="password")
    hf_key = st.text_input("🟠 Hugging Face Token", value=env("HF_TOKEN", ""), type="password")
    groq_key = st.text_input("🟣 Groq API Key", value=env("GROQ_API_KEY", ""), type="password")
    openrouter_key = st.text_input("🟢 OpenRouter API Key", value=env("OPENROUTER_API_KEY", ""), type="password")
    cohere_key = st.text_input("🟡 Cohere API Key", value=env("COHERE_API_KEY", ""), type="password")
    lmstudio_url = st.text_input("⚫ LM Studio Base URL", value=env("LM_STUDIO_BASE_URL", "http://localhost:1234/v1"))

    with st.expander("⚙️ Model Settings", expanded=True):
        gemini_models = get_available_gemini_models(gemini_key)
        gemini_model = st.selectbox("Gemini", gemini_models, index=min(
            max(gemini_models.index("gemini-2.5-flash") if "gemini-2.5-flash" in gemini_models else 0, 0),
            len(gemini_models)-1
        ))
        hf_model = st.text_input("Hugging Face Model", value=DEFAULT_MODELS["Hugging Face"])
        groq_model = st.text_input("Groq Model", value=DEFAULT_MODELS["Groq"])
        openrouter_model = st.text_input("OpenRouter Model", value=DEFAULT_MODELS["OpenRouter"])
        cohere_model = st.text_input("Cohere Model", value=DEFAULT_MODELS["Cohere"])
        lmstudio_model = st.text_input("LM Studio Model", value=DEFAULT_MODELS["LM Studio"])

    provider_keys = {
        "Gemini": gemini_key, "Hugging Face": hf_key, "Groq": groq_key,
        "OpenRouter": openrouter_key, "Cohere": cohere_key,
        "LM Studio": lmstudio_url,
    }
    configured = [p for p, k in provider_keys.items() if k]
    st.caption("Configured: " + (", ".join(configured) if configured else "None"))

    st.markdown("---")
    st.markdown("#### 🗣️ Voice Assistant")
    st.session_state.voice_enabled = st.toggle("Enable voice replies", value=st.session_state.voice_enabled)
    st.session_state.voice_rate = st.slider("Voice speed", 0.7, 1.4, st.session_state.voice_rate, 0.05)
    st.caption("Voice input: Gemini → Hugging Face fallback. Voice output: browser speech synthesis.")

    st.markdown("---")
    st.markdown("#### 🧠 Agent Capabilities")
    for badge in [
        "Gemini", "Hugging Face", "Groq", "OpenRouter", "Cohere", "LM Studio",
        "Live Web", "Python", "Files", "Dev Commands", "Voice I/O"
    ]:
        st.markdown(f"<span class='tool-badge'>{badge}</span>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("#### 📂 Workspace Telemetry")
    file_count = 0
    total_size = 0
    for root, dirs, files in os.walk(WORKSPACE_DIR):
        file_count += len(files)
        for f in files:
            fp = os.path.join(root, f)
            try:
                total_size += os.path.getsize(fp)
            except OSError:
                pass
    col_s1, col_s2 = st.columns(2)
    col_s1.metric("Files", file_count)
    col_s2.metric("Size", f"{round(total_size / 1024, 1)} KB")

    zip_buffer = create_workspace_zip()
    st.download_button(
        "📦 Export Workspace ZIP", data=zip_buffer,
        file_name=f"workspace_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip",
        mime="application/zip", use_container_width=True
    )

    if st.button("🗑️ Reset Workspace", use_container_width=True):
        for item in os.listdir(WORKSPACE_DIR):
            item_path = os.path.join(WORKSPACE_DIR, item)
            if os.path.isfile(item_path) or os.path.islink(item_path):
                os.remove(item_path)
            elif os.path.isdir(item_path):
                shutil.rmtree(item_path)
        os.makedirs(VIDEOS_DIR, exist_ok=True)
        st.success("Workspace reset.")
        st.rerun()

    if st.button("🧹 Clear Chat", use_container_width=True):
        st.session_state.chat_messages = []
        st.rerun()

# ==========================================
# HEADER
# ==========================================
st.markdown("<div class='main-header'>🤖 OmniAgent OS 4</div>", unsafe_allow_html=True)
st.markdown(
    "<div class='sub-header'>Autonomous Agentic AI • Live Web • OpenClaw-style Workspace Automation • Code Runner • Voice Assistant • Image & MP4 Core</div>",
    unsafe_allow_html=True,
)

# ==========================================
# TABS
# ==========================================
tab_chat, tab_code, tab_img, tab_video, tab_files = st.tabs([
    "💬 Autonomous Agent Chat",
    "💻 Code Studio & Runner",
    "🎨 AI Image Studio",
    "🎬 MP4 Video Core",
    "📂 OpenClaw Workspace",
])

# ==========================================
# TAB 1: CHAT + VOICE
# ==========================================
with tab_chat:
    st.caption("One interface for multi-provider AI, live web research, code, files, automation and voice.")

    for idx, msg in enumerate(st.session_state.chat_messages):
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            if msg["role"] == "assistant" and st.session_state.voice_enabled:
                speak_browser(msg["content"], autoplay=False, rate=st.session_state.voice_rate)

    st.markdown(
        "<div class='voice-card'><b>🎙️ Voice Input</b><br>Record a question and OmniAgent will transcribe it, then route it through the same agent workflow.</div>",
        unsafe_allow_html=True
    )

    voice_audio = st.audio_input("Press record and speak to OmniAgent", key="voice_recorder") if hasattr(st, "audio_input") else None
    voice_col1, voice_col2 = st.columns([3, 1])
    with voice_col1:
        user_prompt = st.chat_input("Ask a question, research the web, build code, edit files, or automate a task...")
    with voice_col2:
        process_voice = st.button("🎙️ Use Voice", use_container_width=True)

    voice_prompt = ""
    if process_voice and voice_audio:
        with st.spinner("🎧 Transcribing..."):
            try:
                voice_prompt = transcribe_audio_bytes(
                    voice_audio.getvalue(),
                    api_key=gemini_key,
                    hf_token=hf_key,
                    provider_mode=provider_mode,
                    hf_model="openai/whisper-large-v3-turbo",
                )
                st.success(f"Heard: {voice_prompt}")
            except Exception as exc:
                st.error(f"Voice transcription error: {exc}")
    elif process_voice:
        st.info("Record a voice message first.")

    effective_prompt = voice_prompt or user_prompt

    if effective_prompt:
        st.session_state.chat_messages.append({"role": "user", "content": effective_prompt})
        with st.chat_message("user"):
            st.markdown(effective_prompt)

        with st.chat_message("assistant"):
            placeholder = st.empty()
            status = st.empty()
            try:
                # Current/news requests get live context before fallback providers are used.
                web_context = ""
                if re.search(r"\b(latest|news|today|recent|breaking|headlines|update|updates)\b", effective_prompt, re.I):
                    web_context = web_search(effective_prompt, max_results=6)

                provider_keys = {
                    "Gemini": gemini_key,
                    "Hugging Face": hf_key,
                    "Groq": groq_key,
                    "OpenRouter": openrouter_key,
                    "Cohere": cohere_key,
                    "LM Studio": lmstudio_url,
                }
                chain = choose_provider_chain(provider_mode, provider_keys)
                if not chain:
                    raise RuntimeError("No configured provider for the selected mode. Add an API key or select Auto.")

                model_map = {
                    "Gemini": gemini_model,
                    "Hugging Face": hf_model,
                    "Groq": groq_model,
                    "OpenRouter": openrouter_model,
                    "Cohere": cohere_model,
                    "LM Studio": lmstudio_model,
                }

                history = st.session_state.chat_messages[:-1]
                result_text = ""
                used_provider = None
                errors = []

                with st.spinner("🤖 OmniAgent is routing and completing the task..."):
                    for provider in chain:
                        try:
                            if provider == "Gemini":
                                result_text, used_model = run_gemini_agent(
                                    gemini_key, gemini_model, history, effective_prompt, web_context
                                )
                            else:
                                result_text, used_model = run_text_provider(
                                    provider,
                                    provider_keys[provider],
                                    model_map[provider],
                                    history,
                                    effective_prompt,
                                    web_context,
                                    lmstudio_url=lmstudio_url,
                                )
                            if result_text:
                                used_provider = provider
                                st.session_state.last_agent_model = used_model
                                break
                        except Exception as exc:
                            errors.append(f"{provider}: {type(exc).__name__}: {exc}")
                            if provider_mode != "Auto":
                                raise
                            continue

                if not result_text:
                    raise RuntimeError("All configured providers failed.\n" + "\n".join(errors))

                placeholder.markdown(result_text)
                st.session_state.chat_messages.append({"role": "assistant", "content": result_text})
                status.success(f"Completed with {used_provider} • {st.session_state.last_agent_model}")
                if st.session_state.voice_enabled:
                    speak_browser(result_text, autoplay=False, rate=st.session_state.voice_rate)

            except Exception as e:
                err = f"⚠️ **Agent Error:** {type(e).__name__}: {e}"
                placeholder.markdown(err)
                st.session_state.chat_messages.append({"role": "assistant", "content": err})
                status.error("The request failed. In Auto mode OmniAgent will use another configured provider when possible.")

# ==========================================
# TAB 2: CODE STUDIO
# ==========================================
with tab_code:
    st.subheader("💻 Interactive Code Studio & Python Sandbox")
    col_code_left, col_code_right = st.columns([1, 1])
    with col_code_left:
        st.markdown("##### 📝 Code Editor")
        default_py = """import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x) * np.exp(-0.1 * x)

plt.figure(figsize=(8, 4))
plt.plot(x, y, lw=2.5)
plt.title('Autonomous Code Execution Waveform')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
print('Execution completed! Visualization rendered.')
"""
        code_input = st.text_area("Python Script", value=default_py, height=320, key="sandbox_code")
        c1, c2, c3 = st.columns([1, 1, 1])
        run_btn = c1.button("▶️ Run Code", use_container_width=True, type="primary")
        save_as_file = c2.text_input("Filename", value="script.py", label_visibility="collapsed")
        save_btn = c3.button("💾 Save File", use_container_width=True)
        if save_btn:
            st.success(fs_write_file(save_as_file, code_input))

    with col_code_right:
        st.markdown("##### 🖥️ Execution Console")
        if run_btn:
            with st.spinner("Running Python script in workspace..."):
                exec_result = execute_python_code(code_input)
            if exec_result["stdout"]:
                st.markdown("**Console Output:**")
                st.code(exec_result["stdout"], language="text")
            if exec_result["stderr"]:
                st.markdown("**Errors:**")
                if exec_result["success"]:
                    st.warning(exec_result["stderr"])
                else:
                    st.error(exec_result["stderr"])
            if exec_result["has_plots"]:
                st.markdown("**Generated Visual Charts:**")
                for fig in exec_result["plot_figures"]:
                    st.pyplot(fig)
            if exec_result["success"]:
                st.success("Execution finished successfully.")
        else:
            st.info("Click '▶️ Run Code' to execute the script in the workspace.")

    st.markdown("---")
    st.markdown("##### 🛠️ OpenClaw-style Development Command Runner")
    st.caption("Runs an allowlisted command from the workspace, useful for tests/builds such as `python script.py`, `pip install ...`, `npm run build`, `git status`, or `ffmpeg ...`.")
    cmd_col1, cmd_col2 = st.columns([4, 1])
    with cmd_col1:
        workspace_command = st.text_input("Workspace command", placeholder="python -m pytest")
    with cmd_col2:
        cmd_timeout = st.number_input("Timeout (s)", min_value=1, max_value=180, value=60)
    if st.button("⚙️ Run Workspace Command", type="secondary"):
        if workspace_command:
            with st.spinner("Running command..."):
                result = run_workspace_command(workspace_command, int(cmd_timeout))
            st.code(result, language="json")

# ==========================================
# TAB 3: IMAGE STUDIO
# ==========================================
with tab_img:
    st.subheader("🎨 Generative AI Image Studio")
    img_col1, img_col2 = st.columns([1, 1])
    with img_col1:
        img_prompt_input = st.text_area("Image Prompt:", placeholder="e.g., A cybernetic astronaut exploring an illuminated bioluminescent cave, 8k, cinematic lighting", height=120)
        opt1, opt2, opt3 = st.columns(3)
        aspect = opt1.selectbox("Aspect Ratio", ["1:1 (Square)", "16:9 (Landscape)", "9:16 (Portrait)"])
        model_type = opt2.selectbox("Diffusion Model", ["flux", "turbo"])
        custom_seed = opt3.number_input("Seed (0 for random)", min_value=0, max_value=999999, value=0)
        dim_map = {"1:1 (Square)": (1024, 1024), "16:9 (Landscape)": (1280, 720), "9:16 (Portrait)": (720, 1280)}
        w, h = dim_map[aspect]
        b1, b2 = st.columns(2)
        enhance_btn = b1.button("✨ Enhance Prompt", use_container_width=True)
        generate_img_btn = b2.button("🎨 Render Artwork", type="primary", use_container_width=True)
        if enhance_btn:
            if img_prompt_input and active_api_key:
                with st.spinner("Refining prompt with Gemini..."):
                    enhanced = enhance_prompt_with_gemini(img_prompt_input, active_api_key, "image")
                st.success("Prompt Enhanced!")
                st.text_area("Refined Prompt", value=enhanced, height=80)
            else:
                st.warning("Please provide a prompt and Gemini API Key.")
    with img_col2:
        if generate_img_btn and img_prompt_input:
            with st.spinner("Rendering artwork..."):
                seed_val = None if custom_seed == 0 else custom_seed
                image_url = generate_image_url(img_prompt_input, width=w, height=h, seed=seed_val, model=model_type)
                st.image(image_url, caption=f"Prompt: {img_prompt_input}", use_container_width=True)
                img_bytes = download_media_bytes(image_url)
                if img_bytes:
                    st.download_button("📥 Download Full-Res Image", data=img_bytes, file_name=f"art_{int(time.time())}.jpg", mime="image/jpeg", use_container_width=True)
        else:
            st.info("Enter an image description and click 'Render Artwork'.")

# ==========================================
# TAB 4: VIDEO
# ==========================================
with tab_video:
    st.subheader("🎬 Generative MP4 Video Core")
    st.caption("Synthesizes genuine MP4 video files with dynamic cinematic camera trajectories.")
    vid_col1, vid_col2 = st.columns([1, 1])
    with vid_col1:
        vid_prompt_input = st.text_area("Video Concept Prompt:", placeholder="e.g., A futuristic flying supercar speeding through neon cyberpunk Tokyo in the rain, cinematic lighting", height=120)
        v_c1, v_c2, v_c3 = st.columns(3)
        v_motion = v_c1.selectbox("Camera Trajectory", ["Cinematic Zoom In", "Dynamic Pan Right", "Dramatic Tilt Up", "Orbital Pulse"])
        v_duration = v_c2.selectbox("Duration", [3, 4, 5], index=1)
        v_fps = v_c3.selectbox("Frame Rate", [24, 30], index=0)
        generate_vid_btn = st.button("🎬 Synthesize MP4 Video", type="primary", use_container_width=True)
    with vid_col2:
        if generate_vid_btn and vid_prompt_input:
            with st.spinner("🎬 Synthesizing frames and compiling MP4..."):
                vid_path, vid_bytes = synthesize_ai_video(prompt=vid_prompt_input, motion_type=v_motion, duration_seconds=v_duration, fps=v_fps)
            if vid_bytes and vid_path:
                st.success(f"✅ MP4 generated and saved: `{os.path.basename(vid_path)}`")
                st.video(vid_bytes)
                st.download_button("📥 Download MP4 Video File", data=vid_bytes, file_name=os.path.basename(vid_path), mime="video/mp4", use_container_width=True)
            else:
                st.error("Video synthesis could not be completed. Please try again.")
        else:
            st.info("Enter your video prompt and click 'Synthesize MP4 Video'.")

# ==========================================
# TAB 5: WORKSPACE
# ==========================================
with tab_files:
    st.subheader("📂 OpenClaw-style Workspace File Manager")
    st.caption(f"Active Workspace Root: `{WORKSPACE_DIR}`")
    f_action_col1, f_action_col2, f_action_col3 = st.columns([1, 1, 1])

    with f_action_col1:
        with st.expander("➕ Create New File"):
            new_fname = st.text_input("File Path/Name:", placeholder="notes.txt")
            new_fcontent = st.text_area("Initial Content:", height=100)
            if st.button("Create File", use_container_width=True):
                if new_fname:
                    st.success(fs_write_file(new_fname, new_fcontent))
                    st.rerun()
    with f_action_col2:
        with st.expander("📁 Create New Folder"):
            new_dname = st.text_input("Folder Name:", placeholder="data")
            if st.button("Create Folder", use_container_width=True):
                if new_dname:
                    st.success(fs_create_directory(new_dname))
                    st.rerun()
    with f_action_col3:
        with st.expander("📤 Upload File(s)"):
            uploaded_files = st.file_uploader("Upload to workspace", accept_multiple_files=True)
            if uploaded_files:
                for uf in uploaded_files:
                    target_dest = os.path.join(WORKSPACE_DIR, os.path.basename(uf.name))
                    with open(target_dest, "wb") as f:
                        f.write(uf.getbuffer())
                st.success(f"Uploaded {len(uploaded_files)} file(s)!")
                st.rerun()

    st.markdown("---")
    browser_col, editor_col = st.columns([1, 2])
    with browser_col:
        st.markdown("##### 📁 Workspace Tree")
        st.text_area("Directory Tree", value=fs_list_files(), height=260, disabled=True)
        all_files = []
        for r, _, fls in os.walk(WORKSPACE_DIR):
            for fl in fls:
                all_files.append(os.path.relpath(os.path.join(r, fl), WORKSPACE_DIR))
        selected_file = st.selectbox("Select File to View / Edit:", [""] + sorted(all_files))
        if selected_file:
            if st.button("🗑️ Delete Selected File", type="secondary", use_container_width=True):
                st.warning(fs_delete_path(selected_file))
                st.rerun()

    with editor_col:
        st.markdown("##### 📝 Live File Viewer & Editor")
        if selected_file:
            current_content = fs_read_file(selected_file)
            edited_content = st.text_area(f"Editing: {selected_file}", value=current_content, height=300)
            if st.button("💾 Save File Changes", type="primary", use_container_width=True):
                fs_write_file(selected_file, edited_content)
                st.success(f"File '{selected_file}' updated successfully!")
        else:
            st.info("Select a file from the dropdown on the left to read or edit.")

    with st.expander("🔍 Search in Workspace Files"):
        search_q = st.text_input("Enter keyword to search across all workspace files:")
        if search_q:
            st.code(fs_search_files(search_q), language="text")

    with st.expander("ℹ️ Runtime Information"):
        st.code(get_system_info(), language="json")
